/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.DB4OUtil;
import edu.neu.csye6200.model.Classroom;
import edu.neu.csye6200.model.DayCare;
import edu.neu.csye6200.util.StudentTeacherRatio;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class AddClassRoomDialog extends javax.swing.JDialog {
    DayCare dayCare;
    ClassRoomsView cv;
    DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form AddClassRoomDialog
     */
    public AddClassRoomDialog(DayCare daycare, ClassRoomsView cv) {
        this.dayCare= daycare;
        this.cv = cv;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ageFromLabel = new javax.swing.JLabel();
        confirmAddClassroom = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        ageGroupSelect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        classRoomName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 184, 184));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Classroom Details");

        ageFromLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ageFromLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageFromLabel.setText("Age range");

        confirmAddClassroom.setBackground(new java.awt.Color(77, 144, 254));
        confirmAddClassroom.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        confirmAddClassroom.setForeground(new java.awt.Color(255, 255, 255));
        confirmAddClassroom.setText("Submit");
        confirmAddClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddClassroomActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("*Only number fields are allowed");

        ageGroupSelect.setForeground(new java.awt.Color(255, 255, 255));
        ageGroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ageGroupSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGroupSelectActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        classRoomName.setForeground(new java.awt.Color(102, 102, 102));
        classRoomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoomNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ageFromLabel)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(classRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(ageGroupSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmAddClassroom)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(classRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageGroupSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmAddClassroom)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddClassroomActionPerformed
        try{
            String ageGroup = (String) ageGroupSelect.getSelectedItem();
            String[] groupDes = ageGroup.split("-");
            int ageLower = Integer.parseInt(groupDes[0]);
            int ageHigher = Integer.parseInt(groupDes[1]);
            int groupSize = StudentTeacherRatio.maxGroups[ageGroupSelect.getSelectedIndex()];
            String name = classRoomName.getText();
            JOptionPane.showMessageDialog(this, "New Classroom added successfully");
            Classroom c = new Classroom(ageLower, ageHigher, groupSize, name);
            dayCare.getClassRoomsList().add(c);
            db4OUtil.storeSystem(dayCare);
            ClassRoomsView.handlePostClassroomCreate(this);
            cv.setClassRoomDropDown(dayCare.getClassRoomsList());
            if(dayCare.getClassRoomsList().size()==1){
                cv.setDefaultClassRoom();
            }
            
        }catch(NumberFormatException e){
            errorLabel.setVisible(true);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_confirmAddClassroomActionPerformed

    private void ageGroupSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGroupSelectActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String name = (String)cb.getSelectedItem();
        cb.setSelectedItem(name);        // TODO add your handling code here:
    }//GEN-LAST:event_ageGroupSelectActionPerformed

    private void classRoomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classRoomNameActionPerformed

 
    public void postInit(){
        errorLabel.setVisible(false);
        setAgeGroups();
    }
    
    public void setAgeGroups(){
        String[] classOptions = StudentTeacherRatio.ageGroups;
        int n = classOptions.length;
        String[] options = new String[n];
        for(int i = 0; i< n; i++){
            options[i] = classOptions[i];
        }
        ageGroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(options));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageFromLabel;
    private javax.swing.JComboBox<String> ageGroupSelect;
    private javax.swing.JTextField classRoomName;
    private javax.swing.JButton confirmAddClassroom;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
